# Unbinding C-b
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind l split-window -h
bind j split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Vim keybindings
setw -g mode-keys vi

# pane resizing with vim key bindings 
bind-key -r h resize-pane -L 5
bind-key -r j resize-pane -D 5
bind-key -r k resize-pane -U 5
bind-key -r l resize-pane -R 5

# previous window rebind to prefix + b (we'll use prefix + p for pasting later)
unbind-key b
bind-key b previous-window

# vim copy yank
# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection
# unbind -T copy-mode-vi MouseDragEnd1Pane
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
#
# # vim paste
# unbind-key p
# bind-key p run-shell "pbpaste | tmux load-buffer - && tmux paste-buffer"


# plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sessionist'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# run '~/.tmux/plugins/tpm/tpm'
