[config]
prefer = "closest-to-fallback"
fallback_color = "#6750A4"

[config.wallpaper]
command = "waypaper"
arguments = ["--restore"]
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'killall waybar && waybar & disown'

[templates.hyprland]
input_path = './templates/hypr-colors.lua'
output_path = '~/.config/hypr/modules/generated_colors.lua'
post_hook = 'hyprctl reload'

[templates.wofi]
input_path = "./templates/colors.css"
output_path = "~/.config/wofi/colors.css"

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/config.ghostty'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen-themes'
post_hook = 'killall cava'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
# post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'
