"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "matugen"

format = """
[  ](bg:block1_bg fg:block1_fg)\
[](bg:accent fg:block1_bg)\
$directory\
[](fg:accent bg:block2_bg)\
$git_branch\
$git_status\
[](fg:block2_bg bg:block3_bg)\
$nodejs\
$bun\
$rust\
$golang\
$php\
$c\
$cpp\
$docker_context\
$cmake\
$container\
$elixir\
$ruby\
$gleam\
$gradle\
$java\
$kotlin\
$lua\
$python\
$solidity\
$hostname\
$zig\
$dotnet\
$elixir\
[](fg:block3_bg bg:block4_bg)\
[ ](fg:block4_bg)\
\n$character"""

[character]
success_symbol = "[❯](bold fg:accent)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:accent)"

# Matugen dynamically injects Material You colors into these variables
[palettes.matugen]
block1_bg = '#224876'
block1_fg = '#d4e3ff'
accent    = '#a6c8ff'
accent_fg = '#01315e'
block2_bg = '#43474e'
block3_bg = '#1d2024'
block4_bg = '#111318'

[directory]
style = "fg:accent_fg bg:accent"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:block2_bg"
format = '[[ $symbol $branch ](fg:accent bg:block2_bg)]($style)'

[git_status]
style = "bg:block2_bg"
format = '[[($all_status$ahead_behind )](fg:accent bg:block2_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[rust]
symbol = ""
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[golang]
symbol = ""
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[php]
symbol = ""
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[bun]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[c]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[cpp]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[cmake]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[container]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[docker_context]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[dotnet]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[elixir]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[gleam]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[gradle]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[hostname]
ssh_symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[java]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[kotlin]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[lua]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[python]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[ruby]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[solidity]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[zig]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[meson]
symbol = "󰔷 "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[nix_shell]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[ocaml]
symbol = " "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'

[odin]
symbol = "󰟢 "
style = "bg:block3_bg"
format = '[[ $symbol ($version) ](fg:accent bg:block3_bg)]($style)'
